version: 0.2

phases:
  build:
    commands:
      - dotnet restore
      - dotnet build
      - dotnet publish --framework netcoreapp3.1 --configuration Release --output dist
artifacts:
  files:
    - .\dist\*